package.json, src/App.tsx, src/assets/assets.ts, src/components/AssetDialog.tsx, src/components/AssetListItem.tsx, src/components/CustomInput.tsx, src/components/DialogSwap.tsx, src/components/ListItem.tsx, src/components/PurseDialog.tsx, src/components/PurseListItem.tsx, src/components/SectionSwap.tsx, src/components/SkeletonListItem.tsx, src/components/SkeletonPurseDialog.tsx, src/components/Swap.tsx, src/components/WalletConnection.tsx, src/ertp.d.ts, src/index.css, src/main.tsx, src/store/app.ts, src/styles/base.css, src/styles/components.css, src/styles/globals.css, src/styles/utilities.css, src/utils/displayFunctions.ts, src/utils/helpers.ts, src/utils/updates.ts, src/vite-env.d.ts, tailwind.config.cjs, yarn.lock
refs: https://github.com/Agoric/agoric-sdk/issues/6025
Rips some UI out from `dapp-amm` without much input handling yet.
=> Swap inputs

src/services/swap.ts, src/utils/updates.ts
Minor rename to track Agoric SDK.
=> fix: rename Stable->Minted

mock/brand.mock.ts, package.json, src/components/ContractInfo.tsx, src/components/CustomInput.tsx, src/components/SectionSwap.tsx, src/components/Swap.tsx, src/services/swap.ts, src/store/app.ts, src/store/swap.ts, src/utils/displayFunctions.ts, src/utils/helpers.ts, src/utils/updates.ts, src/vite-env.d.ts, test/utils/helpers.test.ts, vitest.config.ts, yarn.lock
fixes https://github.com/Agoric/agoric-sdk/issues/6340
fixes https://github.com/Agoric/agoric-sdk/issues/6342
fixes https://github.com/Agoric/agoric-sdk/issues/6344
fixes https://github.com/Agoric/agoric-sdk/issues/6345
Screenshots:
=> fix: fix bugs identified in QA party

src/components/ContractInfo.tsx
fixes https://github.com/Agoric/agoric-sdk/issues/6411
=> fix: dont crash when mintLimit is 0

src/components/WalletConnection.tsx
refs https://github.com/Agoric/agoric-sdk/issues/6436
=> chore: rename wallet dropdown to connect wallet

src/App.tsx, src/components/AssetListItem.tsx, src/components/ContractInfo.tsx, src/components/SectionSwap.tsx, src/components/Swap.tsx, src/utils/displayFunctions.ts, src/vite-env.d.ts
Stop-gap for https://github.com/Agoric/agoric-sdk/issues/6458
Remove the foot-gun by simply omitting the MAX button when trading away from IST. We can still do the prevention/warning but I propose that be post-launch.
=> 6458 trading away IST

src/components/AssetListItem.tsx, src/components/DialogSwap.tsx
closes: https://github.com/Agoric/agoric-sdk/issues/6453
=> feat: link to bridging docs

src/components/ChainConnection.tsx, src/components/TermsDialog.tsx, src/store/app.ts
refs: https://github.com/Agoric/agoric-sdk/issues/6491
In draft until we get final confirmation for content/behavior
OLD screenshots:
=> feat: legal dialog

src/components/Swap.tsx, src/store/swap.ts
fixes https://github.com/Agoric/agoric-sdk/issues/6341
=> feat: show more errors for invalid swaps

src/App.tsx, src/components/AnnouncementBanner.tsx, src/store/app.ts
=> feat: show banner about mint limits notice

src/components/AnnouncementBanner.tsx
fixes https://github.com/Agoric/agoric-sdk/issues/6536
=> feat: update banner with raised mint limits

.prettierignore, package.json, tsconfig.json
- build: clean up scripts
- chore: yarn format
unbreaks main test https://github.com/Agoric/dapp-psm/pull/45
=> fixup formatting

src/App.tsx
=> feat: remove banner

src/App.tsx, src/components/Swap.tsx
refs https://github.com/Agoric/dapp-psm/issues/42
=> feat: add analytics link

package.json, src/config.ts, src/store/app.ts, src/utils/updates.ts, yarn.lock
closes https://github.com/Agoric/dapp-psm/issues/56
=> feat: read purses from vbank

src/App.tsx, src/components/AnnouncementBanner.tsx
refs https://github.com/Agoric/dapp-psm/issues/59
Will close issue after upgrade completes and banner is removed
=> feat: pismoc downtime notice

src/components/TermsDialog.tsx
This won't be deployed until the next merge to beta.
=> feat: show disclaimer dialog for new terms

src/App.tsx, src/components/AnnouncementBanner.tsx, yarn.lock
fixes https://github.com/Agoric/dapp-psm/issues/57
=> feat: vaults upgrade notice banner

package.json, yarn.lock
refs https://github.com/Agoric/dapp-inter/issues/151
=> fix: dont hang on empty wallet state

src/App.tsx, src/components/ChainConnection.tsx, src/components/NoticeBanner.tsx, src/store/app.ts, src/utils/networkConfig.ts, test/utils/networkConfig.test.ts, yarn.lock
Merging from another branch rather than main because there were merge conflicts (I think because I had previously pushed banner changes directly to beta that weren't in main)
=> Deploy to production

package.json, yarn.lock
refs https://github.com/Agoric/ui-kit/issues/58
=> fix: dont block when no smart wallet

README.md
Add instructions for displaying banner notice
=> Update README.md with banner notice instructions

src/components/ChainConnection.tsx
Similar to https://github.com/Agoric/dapp-inter/commit/874347f171b59827ea7884afd6b26eaac1f5c8a7
This will remove the need to visit wallet.agoric.app in https://github.com/Agoric/dapp-psm/pull/141 to add the local chain to keplr.
=> feat: suggest chain on wallet connection

package.json, tests/e2e/specs/swap-tokens.spec.js, tests/e2e/utils.js, yarn.lock
Added test that check wallet provisiong in psm on emerynet connection
=> test: testing wallet provisioning in psm

tests/e2e/docker-compose.yml, tests/e2e/specs/swap-tokens.spec.js
changes the tag for the docker image of a3p image in `docker_compose.yml` to the `latest` version instead main which is `deprecated`
=> ci: update a3p version

.github/workflows/e2e_tests.yml, tests/e2e/support.js, tests/e2e/utils.js
updates the e2e test pipeline to also be able to test on the devnet network
=> test: perform e2e tests on devnet

.github/workflows/e2e_tests.yml, README.md, tests/e2e/utils.js
adds xnet as a network to the e2e tests
=> test: added xnet testing in e2e tests
